version: '3.7'
networks:
  laravel:
    
services:
  mydb:
    container_name: "mydb"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /d/server/mysql/data:/var/lib/mysql
      - /d/server/mysql/etc:/etc/mysql
      - /d/server/mysql/log:/var/log/mysql
    networks:
      - laravel
    environment:
      MYSQL_ROOT_PASSWORD: root
    build: ./mysql

  myredis:
      container_name: "myredis"
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - /d/server/redis:/data
      networks:
      - laravel
      build: ./redis

  myphp:
      container_name: "myphp"
      restart: always
      ports:
        - "9000:9000"
      volumes:
        - /d/code:/var/www/html
        - /d/server/php/etc:/usr/local/etc
      networks:
      - laravel
      build: ./php
    
  mynginx:
    container_name: "mynginx"
    restart: always
    ports:
      - "80:80"
    networks:
      - laravel
    volumes:
      - /d/code:/usr/share/nginx/html
      - /d/server/nginx:/etc/nginx
      - /d/server/logs/nginx.logs:/var/log/nginx
    build: ./nginx                             